-- SQLite schema for the tech exam
CREATE TABLE IF NOT EXISTS Person (
  personId INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  document TEXT NOT NULL UNIQUE,
  birthDate DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Account (
  accountId INTEGER PRIMARY KEY AUTOINCREMENT,
  personId INTEGER NOT NULL,
  balance INTEGER NOT NULL DEFAULT 0,
  dailyWithdrawalLimit INTEGER NOT NULL,
  activeFlag BOOLEAN NOT NULL DEFAULT 1,
  accountType INTEGER NOT NULL,
  createDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (personId) REFERENCES Person(personId)
);

CREATE TABLE IF NOT EXISTS Transactions (
  transactionId INTEGER PRIMARY KEY AUTOINCREMENT,
  accountId INTEGER NOT NULL,
  value INTEGER NOT NULL,
  transactionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (accountId) REFERENCES Account(accountId)
);
